apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spommer
  namespace: tbd
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "256M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spommer.intern.dev.nav.no
  strategy:
    type: Recreate
  liveness:
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true