name: Spommer

on:
  workflow_dispatch:
    push:
      paths:
        - 'deploy/**'
        - 'spommer-backend/**'
        - 'spommer-frontend/**'
        - 'build.gradle.kts'
        - '.github/workflows/**'
        - 'Dockerfile'
      branches:
        - main

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'gradle'

      - name: test and build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :spommer-frontend:build :spommmer-backend:test :spommer-backend:build
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Lag Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          cache_from: type=gha
          cache_to: type=gha,mode=max
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: Deploy to dev
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/application.yml
          IMAGE: ${{ needs.build.outputs.image }}
